### ISSUE TITLE
Feature (Wunsch) : cmake Schalter für

### ISSUE THREAD

**Issue by reinhardtA** [JulianSchutsch/requirements#1]
erstellen 
- des Konsolen Tool
- des GuiTool
- beider ... (default)

Hintergrund : QT (widget) Krams ist nicht auf allen Kisten drauf.

**Comment by JulianSchutsch** [comment]
Das ist schmerzhaft wahr, ich habe mich grade damit gequält, es bei mir zum laufen zu bringen. Natürlich wird die endgültige Version mit QT arbeiten. Auf Dauer wird vermutlich auch QT-5 leichter verfügbar sein.

Ich füge eine Option hinzu und werde sie in BUILD Dokumentieren, Schätzung: 1,5 Stunden.

**Comment by JulianSchutsch** [comment]
Letzter Commit auf dem Master enthält die Änderungen.

**Comment by 143828** [comment]
apt-get install qt5-default geht schon seit Wheezy.

**Comment by JulianSchutsch** [comment]
Die Libraries sind auch nicht das Problem, dummerweise fehlt das Qt5WidgetsConfig.cmake.
Dann quält ein noch ein falscher link der libGL, naja...das übliche halt.
Ist übrigens gelöst und läuft.

**Comment by reinhardtA** [comment]
läuft .... nach eine paar sudo apt-get .... und diesem hier
http://askubuntu.com/questions/145887/why-no-library-files-installed-for-google-test
