### ISSUE TITLE
Build error ... Info ...

### ISSUE THREAD

**Issue by reinhardtA** [JulianSchutsch/requirements#2]
Ubuntu 16.04

[ 58%] Building CXX object CMakeFiles/t.dir/test/requirements/commands/test_command_blobs.cpp.o
/home/andreas/Development/requirements/test/requirements/commands/test_command_blobs.cpp: In member function ‘virtual void Commands_NewBlob_Test::TestBody()’:
/home/andreas/Development/requirements/test/requirements/commands/test_command_blobs.cpp:34:20: error: variable ‘std::fstream f’ has initializer but incomplete type
     std::fstream f(fileName, std::fstream::out);
                    ^
/home/andreas/Development/requirements/test/requirements/commands/test_command_blobs.cpp:34:30: error: incomplete type ‘std::fstream {aka std::basic_fstream<char>}’ used in nested name specifier
     std::fstream f(fileName, std::fstream::out);
                              ^
/home/andreas/Development/requirements/test/requirements/commands/test_command_blobs.cpp: In member function ‘virtual void Commands_NewBlob_Console_Test::TestBody()’:
/home/andreas/Development/requirements/test/requirements/commands/test_command_blobs.cpp:59:20: error: variable ‘std::fstream f’ has initializer but incomplete type
     std::fstream f(fileName, std::fstream::out);
                    ^
/home/andreas/Development/requirements/test/requirements/commands/test_command_blobs.cpp:59:30: error: incomplete type ‘std::fstream {aka std::basic_fstream<char>}’ used in nested name specifier
     std::fstream f(fileName, std::fstream::out);
                              ^
/home/andreas/Development/requirements/test/requirements/commands/test_command_blobs.cpp: In member function ‘virtual void Commands_BlobAlias_Test::TestBody()’:
/home/andreas/Development/requirements/test/requirements/commands/test_command_blobs.cpp:80:20: error: variable ‘std::fstream f’ has initializer but incomplete type
     std::fstream f(fileName, std::fstream::out);
                    ^
/home/andreas/Development/requirements/test/requirements/commands/test_command_blobs.cpp:80:30: error: incomplete type ‘std::fstream {aka std::basic_fstream<char>}’ used in nested name specifier
     std::fstream f(fileName, std::fstream::out);
                              ^
CMakeFiles/t.dir/build.make:254: die Regel für Ziel „CMakeFiles/t.dir/test/requirements/commands/test_command_blobs.cpp.o“ scheiterte

**Comment by JulianSchutsch** [comment]
Ja, die impliziten Includes sind die Pest von C++. Hab das #include <fstream> dem test_command_blobs hinzugefügt.

**Comment by reinhardtA** [comment]
klappt!

**Comment by reinhardtA** [comment]
Tests auch : 
[----------] Global test environment tear-down
[==========] 45 tests from 7 test cases ran. (855 ms total)
[  PASSED  ] 45 tests.
