### ISSUE TITLE
Feature Wunsch (convinience) : absoluter Pfad

### ISSUE THREAD

**Issue by reinhardtA** [JulianSchutsch/requirements#4]
In der "req_status.xml" bitte einen absoluten Pdaf eintragen, auch wenn der Nutzer nur einen "relativen" eingibt.
`<?xml version="1.0" ?>
<status>
    <folder>./rq/</folder>
    <selection nr="0">
        <node uuid="5864f2de-cad1-4006-b13d-a4d61cfe0ad1" />
    </selection>
</status>`

Hintergrund ist ein bisschen, dass ich das Tool "installieren" will und dann aus allen Lebenslagen heraus nutzen will - bei relativen Pfaden muss ich mich dann immer im entsprechenden Verzeichnis befinden.

**Comment by JulianSchutsch** [comment]
Das gehört definitiv unter Bugs. Ich werde eben dafür sorgen, daß Folder die entsprechende Boost-Library wieder benutzt.

**Comment by JulianSchutsch** [comment]
Bug mit dem letzten Commit gefixt.
